spring.application.name=Gadget-Store
spring.datasource.url=jdbc:mysql://localhost:3306/gadget_store
spring.datasource.username=root
spring.datasource.password=Sekhar@108

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true